# Generated by Django 6.1 on 2026-08-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("prestado", "Prestado"),
                            ("mantencion", "Mantención"),
                            ("baja", "Baja"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("ubicacion", models.CharField(max_length=150)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
